# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true

- task: Xcode@5
  inputs:
    actions: 'clean build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: '*.xcworkspace'
    scheme: 'sampleapp-ios-swift'
    packageApp: false
    publishJUnitResults: true