default_platform(:ios)

platform :ios do
  desc "Create app on Apple Developer and App Store Connect sites"
  lane :create_app do
    produce
  end

  desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

  desc "Create ipa"
  lane :build do
    enable_automatic_code_signing
    increment_build_number
     update_project_team(
       teamid:"CQPZ5C4VAN"
     )
    gym
  end

  desc "Upload to App Store"
  lane :upload do
    deliver
  end

    desc "Create app, take screenshots, build and upload to App Store"
    lane :do_everything do
     create_app
     screenshot
     build
     upload
    end

end
